// Wallet/OnlineWallet.Web.Core/ClientApp/src/pages/import/subComponents/stockTable.tsx
import * as React from "react";
import { ArticleModel } from "../../../walletApi";

interface StockTableProps { articles: ArticleModel[]; }

const StockTable: React.SFC<StockTableProps> = ({ articles }) => {
    if (articles && articles.length > 0) {
        return (
            <table className="table">
                <thead>
                    <tr>
                        <th>name</th>
                        <th>category</th>
                        <th>occurence</th>
                    </tr>
                </thead>
                <tbody>
                    {articles.map((item, index) =>
                        <tr key={index}>
                            <td>{item.name}</td>
                            <td>{item.category}</td>
                            <td>{item.occurence}</td>
                        </tr>)}
                </tbody>
            </table>
        );
    } else {
        return (
            <div className="jumbotron">
                There is no row to show.
            </div>
        );
    }
};
export { StockTable };

// Wallet/OnlineWallet.Web.Core2/ClientApp/app/import/stock-table/stock-table.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { StockModel } from './StockModel';

@Component({
  moduleId: `${module.id}`,
  selector: 'app-stock-table',
  templateUrl: './stock-table.component.html'
})
export class StockTableComponent implements OnInit {

  @Input()
  stocks: StockModel[];

  constructor() { }

  ngOnInit() {
  }

}

<div *ngIf="stocks && stocks.length; else noElement">
    <table class="table">
        <thead>
          <tr>
            <th>name</th>
            <th>category</th>
            <th>occurence</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let item of stocks">
            <td>{{item.name}}</td>
            <td>{{item.category}}</td>
            <td>{{item.count}}</td>
          </tr>
          <tbody>
      </table>
</div>
<ng-template #noElement>
  <div class="jumbotron">
    There is no row to show.
  </div>
</ng-template>
