// Wallet/OnlineWallet.React/ClientApp/pages/transactions/transactions.component.tsx
import * as React from 'react';
import * as moment from 'moment';
import { TransactionTable, getDirectionColoring } from "common/transactions-view";
import { Transaction, transactionService, walletService, Wallet } from 'walletApi';
import { bind, ListHelpers } from 'walletCommon';
import { Layout } from 'layout';
import { TransactionViewModel, mapTransactionViewModel, mapTransaction } from 'common/models';
import { YearSelector } from 'pages/transactions/yearSelector';
import { MonthSelector } from 'pages/transactions/monthSelector';
import { connect } from 'react-redux';
import { RootState } from 'reducers';

export namespace Transactions {
    export interface Props {
        wallets: Wallet[];
    }

    export interface State {
        changedItems: TransactionViewModel[];
        deletedItems: number[];
        items: TransactionViewModel[];
        selectedYear: number;
        selectedMonth: number;
        maxYear: number;
    }
}

@connect(mapStateToProps)
export class Transactions extends React.Component<Transactions.Props, Transactions.State> {

    constructor(props) {
        super(props);
        const now = new Date();
        this.state = {
            changedItems: [],
            deletedItems: [],
            items: [],
            selectedYear: now.getFullYear(),
            selectedMonth: now.getMonth() + 1,
            maxYear: now.getFullYear()
        };
    }

    componentDidMount() {
        this.dateSelected(this.state.selectedYear, this.state.selectedMonth);
    }

    @bind
    async save() {
        try {
            //this.alertsService.dismissAll();
            if (this.state.changedItems.length === 0 && this.state.deletedItems.length === 0) {
                //this.alertsService.warning("No data has changed.");
                return;
            }
            var transactions = mapTransaction(this.state.changedItems);
            var resultTransactions = await transactionService.batchUpdate(transactions, this.state.deletedItems);
            this.setState({
                changedItems: [],
                deletedItems: []
            });
            //this.alertsService.success("Changes saved successfully.");
        } catch (error) {
            //this.alertsService.error(error);
        }
    }

    @bind
    private deleteItem(item: TransactionViewModel) {
        this.setState((prevState, props) => {
            return {
                items: ListHelpers.remove(prevState.items, item),
                changedItems: ListHelpers.remove(prevState.changedItems, item),
                deletedItems: [...prevState.deletedItems, item.transactionId]
            };
        });
    }

    @bind
    private update(items: TransactionViewModel[], changedItems: TransactionViewModel[]): void {
        this.setState({
            items: items,
            changedItems: changedItems
        });
    }

    @bind
    private yearSelected(year) {
        this.setState({
            selectedYear: year
        }, () => {
            this.dateSelected(this.state.selectedYear, this.state.selectedMonth);
        });
    }

    @bind
    private monthSelected(month: number) {
        this.setState({
            selectedMonth: month
        }, () => {
            this.dateSelected(this.state.selectedYear, this.state.selectedMonth);
        });
    }

    private async dateSelected(year: number, month: number) {
        const start = moment(year + "-" + month + "-01");
        const end = moment(start).endOf("month");
        const result = await transactionService.fetch({
            search: `CreatedAt >= "${start.format("YYYY-MM-DD")}" And CreatedAt <= "${end.format("YYYY-MM-DD")}"`
        });
        this.setState({
            items: mapTransactionViewModel(result, this.props.wallets)
        });
    }

    render() {
        const { maxYear, selectedYear, selectedMonth, items, changedItems } = this.state;
        const { wallets } = this.props;
        return (
            <Layout>
                <form>
                    <div className="form-row">
                        <div className="col">
                            <button type="button" className="btn btn-success" onClick={this.save} name="saveBtn">Save</button>
                        </div>
                        <div className="col">
                            <div className="input-group">
                                <YearSelector from={2009} to={maxYear} year={selectedYear} onChange={this.yearSelected} />
                                <MonthSelector year={selectedYear} month={selectedMonth} onChange={this.monthSelected} />
                            </div>
                        </div>
                    </div>
                </form>
                <TransactionTable changedItems={changedItems} wallets={wallets}
                    items={items} rowColor={getDirectionColoring}
                    deleted={this.deleteItem} update={this.update} />
            </Layout>
        );
    }
}

function mapStateToProps(state: RootState, ownProps: any) {
    return {
        wallets: state.wallets
    };
}

// Wallet/Wallet.Client.Angular/src/app/transactions/transactions.component.ts
import { Component, OnInit, OnChanges, SimpleChanges } from '@angular/core';
import { Transaction, TrasactionsService } from 'walletApi';
import { AlertsService } from 'app/common/alerts';
import { directionColoringFunction } from 'app/common/transaction-view';
import * as moment from "moment";
import { ListHelpers } from 'walletCommon';

@Component({
  selector: 'app-transactions',
  templateUrl: './transactions.component.html',
  styleUrls: ['./transactions.component.scss']
})
export class TransactionsComponent implements OnInit {

  now = moment().startOf("day");
  transactions: Transaction[];
  pageItems: Transaction[];
  changedItems: Transaction[] = [];
  rowColoring = directionColoringFunction;
  selectedYear: string;
  selectedMonth: string;
  months: number[] = [];
  years: number[] = [];

  constructor(
    private trasactionsService: TrasactionsService,
    private alertsService: AlertsService
  ) {
    this.selectedYear = this.now.year().toString();
    this.selectedMonth = (this.now.month() + 1).toString();
  }

  get hasElements() {
    return this.pageItems && this.pageItems.length;
  }

  ngOnInit() {
    this.trasactionsService.fetch({
      sorting: "createdAt desc, transactionId desc"
    }).subscribe(transactions => {
      this.transactions = transactions;
      this.generateDateSelector();
      this.select(this.selectedYear, this.selectedMonth)
    });
  }

  selectYear(year: string) {
    this.select(year, this.selectedMonth);
    this.generateDateSelector();
  }

  selectMonth(month: string) {
    this.select(this.selectedYear, month);
  }

  select(year: string, month: string) {
    var start = moment(year + "-" + month + "-01");
    var end = moment(start).endOf("month");
    this.selectedYear = year;
    this.selectedMonth = month;
    this.pageItems = this.transactions && this.transactions.length
      ? this.transactions.filter(tr => {
        var created = moment(tr.createdAt);
        return created.isSameOrAfter(start) && created.isSameOrBefore(end)
      })
      : [];
  }

  save() {
    this.alertsService.dismissAll();
    if (this.changedItems.length === 0) {
      this.alertsService.warning("No data has changed.");
      return;
    }
    this.trasactionsService.batchUpdate(this.changedItems)
      .subscribe(result => {
        this.changedItems.length = 0;
        this.alertsService.success("Changes saved successfully.");
      });
  }

  monthColor(month: string) {
    var year = parseInt(this.selectedYear);
    var currentMonth = this.now.month() + 1;
    var selectedMonth = parseInt(this.selectedMonth);
    var inspectedMonth = parseInt(month);
    if(inspectedMonth === selectedMonth) {
      return "btn-primary";
    }
    if (year < this.now.year())
      return "btn-default";
    if (year > this.now.year())
      return "disabled";
    return inspectedMonth > currentMonth
      ? "disabled"
      : "btn-default";
  }

  private generateDateSelector() {
    this.years = ListHelpers.createRange(2009, this.now.year());
    //var month = parseInt(this.selectedYear) === this.now.year() ? this.now.month() + 1 : 12;
    this.months = ListHelpers.createRange(1, 12);
  }
}

<div class="row">
    <div class="col-md-12">
        <button type="button" class="btn btn-success" (click)="save()">Save</button>
    </div>
</div>
<app-paged-transaction-table [items]="transactions" [changedItems]="changedItems"></app-paged-transaction-table>
