// Wallet/OnlineWallet.React/ClientApp/pages/transactions/transactions.component.tsx
import * as React from 'react';
import * as moment from 'moment';
import { TransactionTable, getDirectionColoring } from "common/transactions-view";
import { Transaction, transactionService, walletService, Wallet } from 'walletApi';
import { bind, ListHelpers } from 'walletCommon';
import { Layout } from 'layout';
import { TransactionViewModel, mapTransactionViewModel, mapTransaction } from 'common/models';
import { YearSelector } from 'pages/transactions/yearSelector';
import { MonthSelector } from 'pages/transactions/monthSelector';
import { connect } from 'react-redux';
import { RootState } from 'reducers';

export namespace Transactions {
    export interface Props {
        wallets: Wallet[];
    }

    export interface State {
        changedItems: TransactionViewModel[];
        deletedItems: number[];
        items: TransactionViewModel[];
        selectedYear: number;
        selectedMonth: number;
        maxYear: number;
    }
}

@connect(mapStateToProps)
export class Transactions extends React.Component<Transactions.Props, Transactions.State> {

    constructor(props) {
        super(props);
        const now = new Date();
        this.state = {
            changedItems: [],
            deletedItems: [],
            items: [],
            selectedYear: now.getFullYear(),
            selectedMonth: now.getMonth() + 1,
            maxYear: now.getFullYear()
        };
    }

    componentDidMount() {
        this.dateSelected(this.state.selectedYear, this.state.selectedMonth);
    }

    @bind
    async save() {
        try {
            //this.alertsService.dismissAll();
            if (this.state.changedItems.length === 0 && this.state.deletedItems.length === 0) {
                //this.alertsService.warning("No data has changed.");
                return;
            }
            var transactions = mapTransaction(this.state.changedItems);
            var resultTransactions = await transactionService.batchUpdate(transactions, this.state.deletedItems);
            this.setState({
                changedItems: [],
                deletedItems: []
            });
            //this.alertsService.success("Changes saved successfully.");
        } catch (error) {
            //this.alertsService.error(error);
        }
    }

    @bind
    private deleteItem(item: TransactionViewModel) {
        this.setState((prevState, props) => {
            return {
                items: ListHelpers.remove(prevState.items, item),
                changedItems: ListHelpers.remove(prevState.changedItems, item),
                deletedItems: [...prevState.deletedItems, item.transactionId]
            };
        });
    }

    @bind
    private update(items: TransactionViewModel[], changedItems: TransactionViewModel[]): void {
        this.setState({
            items: items,
            changedItems: changedItems
        });
    }

    @bind
    private yearSelected(year) {
        this.setState({
            selectedYear: year
        }, () => {
            this.dateSelected(this.state.selectedYear, this.state.selectedMonth);
        });
    }

    @bind
    private monthSelected(month: number) {
        this.setState({
            selectedMonth: month
        }, () => {
            this.dateSelected(this.state.selectedYear, this.state.selectedMonth);
        });
    }

    private async dateSelected(year: number, month: number) {
        const start = moment(year + "-" + month + "-01");
        const end = moment(start).endOf("month");
        const result = await transactionService.fetch({
            search: `CreatedAt >= "${start.format("YYYY-MM-DD")}" And CreatedAt <= "${end.format("YYYY-MM-DD")}"`
        });
        this.setState({
            items: mapTransactionViewModel(result, this.props.wallets)
        });
    }

    render() {
        const { maxYear, selectedYear, selectedMonth, items, changedItems } = this.state;
        const { wallets } = this.props;
        return (
            <Layout>
                <form>
                    <div className="form-row">
                        <div className="col">
                            <button type="button" className="btn btn-success" onClick={this.save} name="saveBtn">Save</button>
                        </div>
                        <div className="col">
                            <div className="input-group">
                                <YearSelector from={2009} to={maxYear} year={selectedYear} onChange={this.yearSelected} />
                                <MonthSelector year={selectedYear} month={selectedMonth} onChange={this.monthSelected} />
                            </div>
                        </div>
                    </div>
                </form>
                <TransactionTable changedItems={changedItems} wallets={wallets}
                    items={items} rowColor={getDirectionColoring}
                    deleted={this.deleteItem} update={this.update} />
            </Layout>
        );
    }
}

function mapStateToProps(state: RootState, ownProps: any) {
    return {
        wallets: state.wallets
    };
}

// OnlineWallet.Angular/ClientApp/app/transactions/transactions.component.ts
import { Component, OnInit, OnChanges, SimpleChanges } from "@angular/core";
import { Transaction, TransactionsService } from "walletApi";
import { AlertsService } from "app/common/alerts";
import { directionColoringFunction, TransactionViewModel } from "app/common/transaction-view";
import * as moment from "moment";
import { ListHelpers } from "walletCommon";

@Component({
  moduleId: module.id.toString(),
  selector: "app-transactions",
  templateUrl: "./transactions.component.html"
})
export class TransactionsComponent implements OnInit {

  now = moment().startOf("day");
  transactions: Transaction[];
  pageItems: Transaction[];
  changedItems: Transaction[] = [];
  deletedItems: number[] = [];
  rowColoring = directionColoringFunction;
  selectedYear: string;
  selectedMonth: string;
  months: number[] = [];
  years: number[] = [];

  constructor(
    private trasactionsService: TransactionsService,
    private alertsService: AlertsService
  ) {
    this.selectedYear = this.now.year().toString();
    this.selectedMonth = (this.now.month() + 1).toString();
  }

  get hasElements() {
    return this.pageItems && this.pageItems.length;
  }

  ngOnInit() {
    this.trasactionsService.fetch({
      sorting: "createdAt desc, transactionId desc"
    }).subscribe(transactions => {
      this.transactions = transactions;
      this.generateDateSelector();
      this.select(this.selectedYear, this.selectedMonth);
    });
  }

  selectYear(year: string) {
    this.select(year, this.selectedMonth);
    this.generateDateSelector();
  }

  selectMonth(month: string) {
    this.select(this.selectedYear, month);
  }

  select(year: string, month: string) {
    const start = moment(year + "-" + month + "-01");
    const end = moment(start).endOf("month");
    this.selectedYear = year;
    this.selectedMonth = month;
    this.pageItems = this.transactions && this.transactions.length
      ? this.transactions.filter(tr => {
        const created = moment(tr.createdAt);
        return created.isSameOrAfter(start) && created.isSameOrBefore(end);
      })
      : [];
  }

  save() {
    this.alertsService.dismissAll();
    if (this.changedItems.length === 0 && this.deletedItems.length === 0) {
      this.alertsService.warning("No data has changed.");
      return;
    }
    this.trasactionsService.batchUpdate(this.changedItems, this.deletedItems)
      .subscribe(result => {
        this.changedItems.length = 0;
        this.alertsService.success("Changes saved successfully.");
      });
  }

  delete(item: TransactionViewModel) {
    this.transactions = ListHelpers.remove(this.transactions, item.original);
    this.deletedItems.push(item.transactionId);
    this.select(this.selectedYear, this.selectedMonth);
  }

  monthColor(month: string) {
    const year = parseInt(this.selectedYear, 10);
    const currentMonth = this.now.month() + 1;
    const selectedMonth = parseInt(this.selectedMonth, 10);
    const inspectedMonth = parseInt(month, 10);
    if (inspectedMonth === selectedMonth) {
      return "btn-primary";
    }
    if (year < this.now.year()) {
      return "btn-default";
    }
    if (year > this.now.year()) {
      return "disabled";
    }
    return inspectedMonth > currentMonth
      ? "disabled"
      : "btn-default";
  }

  private generateDateSelector() {
    this.years = ListHelpers.createRange(2009, this.now.year());
    this.months = ListHelpers.createRange(1, 12);
  }
}

<form class="form-inline">
    <button type="button" class="btn btn-success" (click)="save()" name="saveBtn">Save</button>
    <div class="input-group pull-right">
        <select class="form-control" [ngModel]="selectedYear" (ngModelChange)="selectYear($event)" name="selectedYear">
          <option *ngFor="let year of years" [value]="year">{{year}}</option>
        </select>
        <div class="input-group-btn">
            <button *ngFor="let month of months" class="btn" type="button" (click)="selectMonth(month)" [ngClass]="monthColor(month)"
                name="selectedMonth">{{ month }}</button>
        </div>
    </div>
</form>
<app-balance class="row" [year]="selectedYear" [month]="selectedMonth"></app-balance>
<ng-container *ngIf="hasElements; else noElement">
    <app-transaction-table [items]="pageItems" [changedItems]="changedItems" [rowModifier]="rowColoring" (deleted)="delete($event)"></app-transaction-table>
</ng-container>
<ng-template #noElement>
    <div class="jumbotron">
        There is no row to show.
    </div>
</ng-template>
