// Wallet/OnlineWallet.Web.Core/ClientApp/common/transactions-view/transaction-table/transaction-table.tsx
import * as React from "react";
import "./transaction-table.scss";
import { Wallet, Transaction, walletService } from "walletApi";
import { ITransactionTableExtFunction } from "../models";
import { _, bind } from "walletCommon";
import { TransactionTableRow } from "./transaction-table-row";
import { TransactionViewModel } from "common/models";

export namespace TransactionTable {
  export interface Props {
    items: TransactionViewModel[];
    wallets: Wallet[];
    changedItems?: TransactionViewModel[];
    rowColor?: ITransactionTableExtFunction;
    update(items: TransactionViewModel[], changedItems?: TransactionViewModel[]): void;
    deleted(items: TransactionViewModel): void;
  }

  export interface State {
  }
}

export class TransactionTable extends React.Component<TransactionTable.Props, TransactionTable.State> {

  constructor(props: TransactionTable.Props) {
    super(props);
    this.state = {
      wallets: []
    };
  }

  @bind
  saveTransaction(newItem: TransactionViewModel, original: TransactionViewModel) {
    let items = _.replace(this.props.items, newItem, original);
    let changes = this.props.changedItems ? _.replace(this.props.changedItems, newItem, original, true) : undefined;
    this.props.update(items, changes);
  }

  @bind
  deleteTransaction(item: TransactionViewModel) {
    this.props.deleted(item);
  }

  render() {
    const { items, wallets, rowColor } = this.props;
    return (
      <table className="table transactions">
        <thead>
          <tr>
            <th className="created-at">createdAt</th>
            <th className="name">name</th>
            <th className="direction">dir</th>
            <th className="price">price</th>
            <th className="wallet-name">walletName</th>
            <th className="category">category</th>
            <th>comment</th>
            <th className="commands"></th>
          </tr>
        </thead>
        <tbody>
          {items.map(item =>
            <TransactionTableRow
              key={item.key}
              item={item}
              wallets={wallets}
              deleteTransaction={this.deleteTransaction}
              saveTransaction={this.saveTransaction}
              rowColor={rowColor} />)}
        </tbody>
      </table>
    );
  }
}

// Wallet/OnlineWallet.Web.Core/ClientApp/app/common/transaction-view/transaction-table/transaction-table.component.ts
import { Component, OnInit, Input, EventEmitter, Output, OnChanges, SimpleChanges } from '@angular/core';
import { TransactionViewModel, ITransactionTableExtFunction } from '../models';
import { Wallet, Transaction, WalletService } from 'walletApi';
import { ListHelpers } from 'walletCommon';

@Component({
  selector: 'app-transaction-table',
  templateUrl: './transaction-table.component.html',
  styleUrls: ['./transaction-table.component.scss']
})
export class TransactionTableComponent implements OnInit, OnChanges {

  wallets: Wallet[];

  pageItems: TransactionViewModel[];

  @Input("items")
  items: Transaction[];

  @Input("changedItems")
  changedItems: Transaction[];

  @Input("rowModifier")
  rowModifier: ITransactionTableExtFunction;

  @Output()
  deleted = new EventEmitter<TransactionViewModel>();

  constructor(
    private walletService: WalletService
  ) { }

  ngOnInit() {
    this.walletService.getAll().subscribe(value => {
      this.wallets = value;
      if (this.pageItems && this.pageItems.length) {
        this.pageItems.forEach(item => this.setWalletName(item));
      }
    });
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes["items"]) {
      this.loadItems();
    }
  }

  loadItems() {
    this.pageItems = this.items ? this.items.map(v => new TransactionViewModel(v)) : [];

    this.pageItems.forEach(item => {
      this.setWalletName(item); 
      if (this.rowModifier) {
        this.rowModifier(item);
      }
    });
  }

  editTransaction(item: TransactionViewModel) {
    item.editMode = !item.editMode;
  }

  deleteTransaction(item: TransactionViewModel) {
    ListHelpers.remove(this.items, item.original);
    this.deleted.emit(item);
  }

  saveTransaction(item: TransactionViewModel) {
    for (var key in item.original) {
      if (item.original.hasOwnProperty(key)) {
        if (item.original[key] !== item[key]) {
          item.original[key] = item[key];
          item.changed = true;
        }
      }
    }
    this.setWalletName(item);
    item.editMode = false;
    if (this.changedItems) {
      var changes = this.pageItems.filter(val => val.changed);
      for (var index = 0; index < changes.length; index++) {
        var item = changes[index];
        if (this.changedItems.findIndex(e => e === item.original) === -1) {
          this.changedItems.push(item.original);
        }
      }
    }
  }
  private setWalletName(item: TransactionViewModel) {
    item.walletName = ListHelpers.selectMap<Wallet, string>(this.wallets, w => w.moneyWalletId == item.walletId, w => w.name);
  }
}

<table class="table">
  <thead>
    <tr>
      <th class="created-at">createdAt</th>
      <th class="name">name</th>
      <th class="direction">dir</th>
      <th class="price">price</th>
      <th class="wallet-name">walletName</th>
      <th class="category">category</th>
      <th>comment</th>
      <th class="commands"></th>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let item of pageItems" [ngClass]="item.cssClass">
      <ng-container *ngIf="item.editMode; then editRow; else viewRow"></ng-container>
      <ng-template #editRow>
        <td><input type="date" class="form-control" [(ngModel)]="item.createdAtText" name="createdAt" /></td>
        <td><input type="text" class="form-control" [(ngModel)]="item.name" name="name" /></td>
        <td (click)="changeDirection(item)">
            <span *ngIf="item.direction===-1" class="glyphicon glyphicon-minus text-danger"></span>
            <span *ngIf="item.direction===1" class="glyphicon glyphicon-plus text-success"></span>
            <span *ngIf="item.direction===0" class="glyphicon glyphicon-bookmark"></span>
        </td>
        <td><input type="number" class="form-control" [(ngModel)]="item.value" name="value" /></td>
        <td>
          <select class="form-control" [(ngModel)]="item.walletId" name="walletId">
              <option *ngFor="let wallet of wallets" [value]="wallet.moneyWalletId">{{wallet.name}}</option>
            </select>
        </td>
        <td><input type="category" class="form-control" [(ngModel)]="item.category" name="category" /></td>
        <td><input type="comment" class="form-control" [(ngModel)]="item.comment" name="comment" /></td>
        <td>
          <button class="btn btn-danger btn-sm pull-right" type="button" (click)="item.cancel()">
                <span class="glyphicon glyphicon-remove"></span>
              </button>
          <button class="btn btn-success btn-sm pull-right" type="button" (click)="saveTransaction(item)">
                <span class="glyphicon glyphicon-ok"></span>
              </button>
        </td>
      </ng-template>
      <ng-template #viewRow>
        <td>{{item.createdAtText}}</td>
        <td>{{item.name}}</td>
        <td>
            <span *ngIf="item.direction===-1" class="glyphicon glyphicon-minus text-danger"></span>
            <span *ngIf="item.direction===1" class="glyphicon glyphicon-plus text-success"></span>
            <span *ngIf="item.direction===0" class="glyphicon glyphicon-bookmark"></span>
        </td>
        <td>{{item.value}}</td>
        <td>{{item.walletName}}</td>
        <td>{{item.category}}</td>
        <td>{{item.comment}}</td>
        <td>
          <button class="btn btn-danger btn-sm pull-right" type="button" (click)="deleteTransaction(item)">
                <span class="glyphicon glyphicon-trash"></span>
              </button>
          <button class="btn btn-primary btn-sm pull-right" type="button" (click)="editTransaction(item)">
                <span class="glyphicon glyphicon-edit"></span>
              </button>
        </td>
      </ng-template>
    </tr>
  </tbody>
</table>
