// Wallet/OnlineWallet.React/ClientApp/pages/home/home.component.tsx
import * as React from 'react';
import * as moment from 'moment';
import { bindActionCreators } from 'redux';
import { connect } from 'react-redux';
import { RouteComponentProps } from 'react-router';
import { walletService, Wallet, Transaction, MoneyDirection, transactionService } from "walletApi";
import { Layout } from 'layout';
import { TransactionTable, getDirectionColoring } from 'common/transactions-view';
import { bind, updateState, ListHelpers } from 'walletCommon';
import { FormGroup, WalletSelector, NameInput } from 'common/misc';
import { toDateString, TransactionViewModel, mapTransaction, getWalletNameById } from 'common/models';
import { DirectionCheck } from 'pages/home/directionCheck';

export namespace Home {
    export interface Props {

    }

    export interface State {
        wallets: Wallet[];
        items: TransactionViewModel[];
        newItem: TransactionViewModel;
        id: number;
    }
}

export class Home extends React.Component<Home.Props, Home.State> {
    nameInput: NameInput;

    /**
     *
     */
    constructor() {
        super();
        this.state = {
            wallets: [],
            items: [],
            newItem: this.emptyItem(1),
            id: 1
        };
    }

    componentDidMount() {
        walletService.getAll()
            .then(wallets => {
                this.setState({
                    wallets: wallets
                })
            })
    }

    @bind
    deleteRow(item: TransactionViewModel) {
        this.setState((prevState, props) => {
            return {
                items: ListHelpers.remove(prevState.items, item),
            };
        });
    }

    @bind
    updateRow(items: TransactionViewModel[]) {
        this.setState((prevState, props) => {
            return {
                items: items,
            };
        });
    }

    @bind
    handleInputChange(event: React.SyntheticEvent<HTMLFormElement>) {
        var state = updateState(event);
        if (state.walletId) {
            state.walletId = parseInt(state.walletId, 10);
        }
        if (state.direction) {
            state.direction = parseInt(state.direction, 10);
        }
        this.setState((prevState, props) => {
            var newItem = { ...prevState.newItem, ...state };
            newItem.cssClass = getDirectionColoring(newItem);
            return {
                newItem
            };
        });
    }

    @bind
    addLine(event: React.ChangeEvent<HTMLFormElement>) {
        event.preventDefault();
        this.setState((prevState, props) => {
            var item: TransactionViewModel = {
                ...prevState.newItem,
                walletName: getWalletNameById(prevState.newItem.walletId, prevState.wallets)
            };
            return {
                items: [...prevState.items, prevState.newItem],
                newItem: {
                    ...prevState.newItem,
                    name: "",
                    category: "",
                    comment: "",
                    price: "",
                    key: prevState.id + 1
                },
                id: prevState.id + 1
            };
        }, () => {
            const nameInput = this.nameInput;
            nameInput.focus();
        });
    }

    @bind
    async saveAll() {
        try {
            //this.alertsService.dismissAll();
            if (!this.state.items.length) {
                //this.alertsService.warning("Nothing to save");
                return;
            }
            var serverItems = mapTransaction(this.state.items);
            var result = await transactionService.batchUpdate(serverItems);
            //this.alertsService.success("Transactions are saved successfully.");
            this.setState({
                items: [],
                newItem: this.emptyItem(1),
                id: 1
            });
        } catch (e) {
            //this.alertsService.error(error.message);
        }
    }
    /* Something is wrong:
    <FormGroup name="createdAt" label="Date">
        <input type="text" className="form-control" id="createdAt" name="createdAt" value={this.state.newItem.createdAt} />
    </FormGroup>
    */
    render() {
        return (
            <Layout>
                <form onChange={this.handleInputChange} onSubmit={this.addLine}>
                    <FormGroup name="walletId" label="Wallet">
                        <WalletSelector walletId={this.state.newItem.walletId} wallets={this.state.wallets} />
                    </FormGroup>
                    <FormGroup name="createdAt" label="Date" type="date" value={this.state.newItem.createdAt} />
                    <FormGroup name="name" label="Name">
                        <NameInput ref={(input) => this.nameInput = input} value={this.state.newItem.name} autoFocus={true} />
                    </FormGroup>
                    <FormGroup name="price" label="Price" type="number" value={this.state.newItem.price} />
                    <FormGroup name="comment" label="Comment" value={this.state.newItem.comment} />
                    <FormGroup name="category" label="Category" value={this.state.newItem.category} />
                    <DirectionCheck value={this.state.newItem.direction} />
                    <button type="submit" className="btn btn-primary">Add</button>
                    <button type="button" className="btn btn-success" onClick={this.saveAll}>Save</button>
                </form>
                <TransactionTable items={this.state.items} deleted={this.deleteRow} update={this.updateRow} rowColor={getDirectionColoring} />
            </Layout>
        );
    }

    private emptyItem(id: number): TransactionViewModel {
        return {
            walletId: 2,
            createdAt: toDateString(new Date()),
            direction: MoneyDirection.Expense,
            name: "",
            price: "",
            walletName: "",
            comment: "",
            category: "",
            key: id
        };
    }
}

// Wallet/OnlineWallet.Web.Core/ClientApp/app/home/home.component.ts
import { Component, OnInit, ViewChild, HostListener } from '@angular/core';
import { Transaction, WalletService, Wallet, ApiError } from "walletApi";
import { ListHelpers } from 'walletCommon';
import { ICleanForm } from 'app/common/ask-if-form-dirty.service';
import { TransactionsService } from 'walletApi';
import { AlertsService } from 'app/common/alerts';
import { TransactionViewModel, directionColoringFunction } from 'app/common/transaction-view';
import { AddTransactionComponent } from 'app/home/add-transaction/add-transaction.component';

@Component({
  moduleId: module.id.toString(),
  selector: 'app-home',
  templateUrl: './home.component.html'
})
export class HomeComponent implements OnInit, ICleanForm {

  linesToSave: Transaction[];
  wallets: Wallet[] = [];
  rowColoring = directionColoringFunction;

  @ViewChild(AddTransactionComponent)
  addTransaction: AddTransactionComponent;

  constructor(
    private walletService: WalletService,
    private transactionsService: TransactionsService,
    private alertsService: AlertsService) {

  }

  startNew() {
    this.linesToSave = [];
  }

  ngOnInit() {
    this.startNew();
    this.walletService.getAll().subscribe(value => {
      this.wallets = value;
    }, (error: ApiError) => {
      this.alertsService.error(error.message);
    });
  }

  addLine(newItem: Transaction) {
    this.linesToSave = this.linesToSave.concat(newItem);
  }

  saveAll() {
    this.alertsService.dismissAll();
    if (!this.linesToSave.length) {
      this.alertsService.warning("Nothing to save");
      return;
    }
    this.transactionsService.batchUpdate(this.linesToSave).subscribe(result => {

      this.alertsService.success("Transactions are saved successfully.");
      this.startNew();
      this.addTransaction.clearFields();
    }, error => {
      this.alertsService.error(error.message);
    });
  }

  delete(item: TransactionViewModel) {
    this.linesToSave = ListHelpers.remove(this.linesToSave, item.original);
  }

  walletNameById(walletId: number) {
    return ListHelpers.selectMap(this.wallets,
      wallet => wallet.moneyWalletId === walletId,
      wallet => wallet.name);
  }

  @HostListener('window:beforeunload')
  isCleanForm() {
    return !this.linesToSave.length;
  }
}

<section class="row">
  <app-add-transaction (add)="addLine($event)" [wallets]="wallets" (save)="saveAll($event)">
  </app-add-transaction>
</section>
<section class="row">
  <app-transaction-table [items]="linesToSave" [rowModifier]="rowColoring" (deleted)="transactionDeleted($event)"></app-transaction-table>
</section>
