// Etc/OnlineWallet.Angular/ClientApp/app/common/transaction-view/transaction-table/transaction-table.component.ts
import { Component, OnInit, Input, EventEmitter, Output, OnChanges, SimpleChanges } from "@angular/core";
import { TransactionViewModel, ITransactionTableExtFunction } from "../models";
import { Wallet, Transaction, WalletService, MoneyDirection } from "walletApi";
import { ListHelpers } from "walletCommon";

@Component({
  moduleId: module.id.toString(),
  selector: "app-transaction-table",
  templateUrl: "./transaction-table.component.html",
  styleUrls: ["./transaction-table.component.scss"]
})
export class TransactionTableComponent implements OnInit, OnChanges {

  wallets: Wallet[];

  pageItems: TransactionViewModel[];

  @Input("items")
  items: Transaction[];

  @Input("changedItems")
  changedItems: Transaction[];

  @Input("rowModifier")
  rowModifier: ITransactionTableExtFunction;

  @Output("deleted")
  deleted = new EventEmitter<TransactionViewModel>();

  constructor(
    private walletService: WalletService
  ) { }

  ngOnInit() {
    this.walletService.getAll().subscribe(value => {
      this.wallets = value;
      if (this.pageItems && this.pageItems.length) {
        this.pageItems.forEach(item => this.setWalletName(item));
      }
    });
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes["items"]) {
      this.loadItems();
    }
  }

  loadItems() {
    this.pageItems = this.items ? this.items.map(v => new TransactionViewModel(v)) : [];

    this.pageItems.forEach(item => {
      this.setWalletName(item);
      if (this.rowModifier) {
        this.rowModifier(item);
      }
    });
  }

  changeDirection(item: TransactionViewModel) {
    switch (item.direction) {
      case MoneyDirection.Expense:
        item.direction = MoneyDirection.Income;
        break;
      case MoneyDirection.Income:
        item.direction = MoneyDirection.Plan;
        break;
      case MoneyDirection.Plan:
        item.direction = MoneyDirection.Expense;
        break;
    }
  }

  editTransaction(item: TransactionViewModel) {
    item.editMode = !item.editMode;
  }

  deleteTransaction(item: TransactionViewModel) {
    this.deleted.emit(item);
  }

  saveTransaction(item: TransactionViewModel) {
    for (const key in item.original) {
      if (item.original.hasOwnProperty(key)) {
        if (item.original[key] !== item[key]) {
          item.original[key] = item[key];
          item.changed = true;
        }
      }
    }
    this.setWalletName(item);
    item.editMode = false;
    if (this.changedItems) {
      const changes = this.pageItems.filter(val => val.changed);
      for (let index = 0; index < changes.length; index++) {
        const cangedItem = changes[index];
        if (this.changedItems.findIndex(e => e === cangedItem.original) === -1) {
          this.changedItems.push(cangedItem.original);
        }
      }
    }
  }

  private setWalletName(item: TransactionViewModel) {
    item.walletName = ListHelpers.selectMap<Wallet, string>(this.wallets, w => w.moneyWalletId === item.walletId, w => w.name);
  }
  
  private directionCssClass(item: TransactionViewModel) {
    switch (item.direction) {
      case -1:
        return "glyphicon glyphicon-minus text-danger";
      case 1:
        return "glyphicon glyphicon-plus text-success";
      default:
        return "glyphicon glyphicon-bookmark";
    }
  }
}

<table class="table">
  <thead>
    <tr>
      <th class="created-at">createdAt</th>
      <th class="name">name</th>
      <th class="direction">dir</th>
      <th class="price">price</th>
      <th class="wallet-name">walletName</th>
      <th class="category">category</th>
      <th>comment</th>
      <th class="commands"></th>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let item of pageItems" [ngClass]="item.cssClass">
      <ng-container *ngIf="item.editMode; then editRow; else viewRow"></ng-container>
      <ng-template #editRow>
        <td><input type="date" class="form-control" [(ngModel)]="item.createdAtText" name="createdAt" /></td>
        <td><input type="text" class="form-control" [(ngModel)]="item.name" name="name" /></td>
        <td (click)="changeDirection(item)">
          <span [ngClass]="directionCssClass(item)"></span>
        </td>
        <td><input type="number" class="form-control" [(ngModel)]="item.value" name="value" /></td>
        <td>
          <select class="form-control" [(ngModel)]="item.walletId" name="walletId">
              <option *ngFor="let wallet of wallets" [value]="wallet.moneyWalletId">{{wallet.name}}</option>
            </select>
        </td>
        <td><input type="text" class="form-control" [(ngModel)]="item.category" name="category" /></td>
        <td><input type="text" class="form-control" [(ngModel)]="item.comment" name="comment" /></td>
        <td>
          <button class="btn btn-danger btn-sm pull-right" type="button" (click)="item.cancel()">
            <span class="glyphicon glyphicon-remove"></span>
          </button>
          <button class="btn btn-success btn-sm pull-right" type="button" (click)="saveTransaction(item)">
            <span class="glyphicon glyphicon-ok"></span>
          </button>
        </td>
      </ng-template>
      <ng-template #viewRow>
        <td>{{item.createdAtText}}</td>
        <td>{{item.name}}</td>
        <td>
            <span [ngClass]="directionCssClass(item)"></span>
        </td>
        <td>{{item.value}}</td>
        <td>{{item.walletName}}</td>
        <td>{{item.category}}</td>
        <td>{{item.comment}}</td>
        <td>
          <button class="btn btn-danger btn-sm pull-right" type="button" (click)="deleteTransaction(item)">
                <span class="glyphicon glyphicon-trash"></span>
              </button>
          <button class="btn btn-primary btn-sm pull-right" type="button" (click)="editTransaction(item)">
                <span class="glyphicon glyphicon-edit"></span>
              </button>
        </td>
      </ng-template>
    </tr>
  </tbody>
</table>

// Wallet/OnlineWallet.React/ClientApp/common/transactions-view/transaction-table/transaction-table.component.tsx
import * as React from "react";
import { Wallet, Transaction } from "walletApi";
import { TransactionViewModel, ITransactionTableExtFunction } from "../models";
import { ListHelpers } from "walletCommon";
import { TransactionTableRow } from "./transaction-table-row.component";

export namespace TransactionTable {
  export interface Props {
    items: Transaction[];
    changedItems: Transaction[];
    rowModifier: ITransactionTableExtFunction;
    deleted(item: TransactionViewModel): void;
  }

  export interface State {
    wallets: Wallet[];
    pageItems: TransactionViewModel[];
  }
}

export class TransactionTable extends React.Component<TransactionTable.Props, TransactionTable.State> {
  saveTransaction(item: TransactionViewModel) {
    for (const key in item.original) {
      if (item.original.hasOwnProperty(key)) {
        if (item.original[key] !== item[key]) {
          item.original[key] = item[key];
          item.changed = true;
        }
      }
    }
    this.setWalletName(item);
    item.editMode = false;
    if (this.props.changedItems) {
      const changes = this.state.pageItems.filter(val => val.changed);
      for (let index = 0; index < changes.length; index++) {
        const cangedItem = changes[index];
        if (this.props.changedItems.findIndex(e => e === cangedItem.original) === -1) {
          this.props.changedItems.push(cangedItem.original);
        }
      }
    }
  }
  editTransaction(item: TransactionViewModel) {
    item.editMode = !item.editMode;
  }

  deleteTransaction(item: TransactionViewModel) {
    this.props.deleted(item);
  }

  private setWalletName(item: TransactionViewModel) {
    item.walletName = ListHelpers.selectMap<Wallet, string>(this.state.wallets, w => w.moneyWalletId === item.walletId, w => w.name);
  }

  render() {
    return (
      <table className="table">
        <thead>
          <tr>
            <th className="created-at">createdAt</th>
            <th className="name">name</th>
            <th className="direction">dir</th>
            <th className="price">price</th>
            <th className="wallet-name">walletName</th>
            <th className="category">category</th>
            <th>comment</th>
            <th className="commands"></th>
          </tr>
        </thead>
        <tbody>
          {this.state.pageItems.map(item => 
            <TransactionTableRow 
              key={item.transactionId} 
              item={item} 
              wallets={this.state.wallets} 
              deleteTransaction={this.deleteTransaction}
              rowModifier={this.props.rowModifier}
              saveTransaction={this.saveTransaction} />)}
        </tbody>
      </table>
    );
  }
}
