// Wallet/OnlineWallet.React/ClientApp/pages/transactions/subComponents/balance.tsx
import * as React from 'react';
import { BalanceInfo } from 'walletApi';

export namespace Balance {
    export interface Props {
        balance: BalanceInfo;
    }
    export interface State {
    }
}

export class Balance extends React.Component<Balance.Props, Balance.State> {
    constructor(props) {
        super(props);
    }
    render() {
        var { balance } = this.props;
        if (!balance)
            return null;
        return (
            <article className="row">
                <div className="col-sm"><span>Income:</span><strong>{balance.income}</strong></div>
                <div className="col-sm"><span>Spent:</span><strong>{balance.spent}</strong></div>
                <div className="col-sm"><span>Saving:</span><strong>{balance.toSaving}</strong></div>
                <div className="col-sm"><span>Planned:</span><strong>{balance.planned}</strong></div>
                <div className="w-100"></div>
                <div className="col-sm"><span>Unused:</span><strong>{balance.unused}</strong></div>
            </article>
        );
    }
}

// Wallet/OnlineWallet.Web.Core/ClientApp/app/transactions/balance/balance.component.ts
import { Component, OnInit, Input, OnChanges, SimpleChanges } from '@angular/core';
import { TransactionsService, BalanceInfo } from 'walletApi';

@Component({
  selector: 'app-balance',
  templateUrl: './balance.component.html',
  styleUrls: ['./balance.component.scss']
})
export class BalanceComponent implements OnInit, OnChanges {

  @Input()
  year: number;

  @Input()
  month: number;

  balance: BalanceInfo = {};

  constructor(
    private transactionsService: TransactionsService
  ) { }

  ngOnInit() {
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (this.year && this.month) {
      this.transactionsService.balanceInfo(this.year, this.month)
        .subscribe(balance => {
          this.balance = balance || {};
        });
    }
  }
}

<div class="col-sm-3"><span>Income:</span><strong>{{balance.income}}</strong></div>
<div class="col-sm-3"><span>Spent:</span><strong>{{balance.spent}}</strong></div>
<div class="col-sm-3"><span>Saving:</span><strong>{{balance.toSaving}}</strong></div>
<div class="col-sm-3"><span>Planned:</span><strong>{{balance.planned}}</strong></div>
<div class="col-sm-3"><span>Unused:</span><strong>{{balance.unused}}</strong></div>
